test_that("daily_averages works", {
  activities_complete <- data.frame(act_id = c(0, 1),
                                    pop_id = c(2, 3),
                                    date = c("2020-12-20", "2020-12-20"),
                                    time = c(1, 1),
                                    time_label = c("04:00-04:10", "04:00-04:10"),
                                    activity = c(110, 110),
                                    activity_label = c("Sleep", "Sleep"),
                                    location = c(11, 11),
                                    location_label = c("Home", "Home"),
                                    hour = c(4, 4),
                                    day_label = c("Sunday", "Sunday"),
                                    day = c(1, 1),
                                    daytype = c(1, 1),
                                    daytype_label = c("Weekend", "Weekend"),
                                    season = c(1, 1),
                                    season_label = c("Winter", "Winter"),
                                    micro_group = c("home", "home"),
                                    area_id = c("", ""),
                                    sex = c(0, 1),
                                    sex_label = c("Female", "Male"),
                                    agegr4 = c(6, 5),
                                    agegr4_label = c("", ""),
                                    nssec5 = c(2, 2),
                                    nssec5_label = c("", ""),
                                    pm25_cams_agg = c(1.0, 1.0),
                                    pm25_five = c(5, 5),
                                    pm25_emep_agg = c(1.0, 1.0),
                                    pm25_cams_agg_tns = c(60.0, 60.0),
                                    pm25_emep_agg_tns = c(40.0, 40.0),
                                    pm25_five_tns = c(30.0, 30.0),
                                    pm25_cams_agg_inh = c(10.0, 10.0),
                                    pm25_emep_agg_inh = c(10.0, 10.0),
                                    pm25_five_inh = c(10.0, 10.0),
                                    uniid = c(1, 1),
                                    pm25_cams_agg_hhd = c(10.0, 10.0),
                                    pm25_emep_agg_hhd = c(10.0, 10.0),
                                    pm25_five_hhd = c(10.0, 10.0))

  expected <- data.frame()
  actual <- daily_averages(activities_complete)
  expect_equal(actual, expected)
})
